### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\apps\\com.whatsapp\\db\\msgstore.db'

### ISSUE THREAD

**Issue by Mi-nk** [mukulkadel/mwatoi#2]
Getting this error after enabling debugging, 

Starting backup process.
Uninstalling current apk.
Success
Installing WhatsApp 2.11.431.
Performing Streamed Install
adb: failed to install bin\LegacyWhatsApp.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
Installation complete!
Backing up data.

Note: Please don't enter any password.

WARNING: adb backup is deprecated and may be removed in a future release
Now unlock your device and confirm the backup operation...
Extracting tmp\whatsapp.ab file.
Creating out directory.
Copying android db
Traceback (most recent call last):
  File "F:\whatsaoo\mwatoi-master\main.py", line 76, in <module>
    shutil.copyfile('tmp\\apps\\com.whatsapp\\db\\msgstore.db','out\\android.db')
  File "C:\Users\spell\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp\\apps\\com.whatsapp\\db\\msgstore.db'

**Comment by Mi-nk** [comment]
Device is Redmi note 10G btw ;)

**Comment by Mi-nk** [comment]
Had to disable MUI optimizations
