### ISSUE TITLE
Compressed file ended before the end-of-stream marker was reached

### ISSUE THREAD

**Issue by michelebanfi** [mukulkadel/mwatoi#3]
Hi when i was using the code and its gets this error
```
WARNING: adb backup is deprecated and may be removed in a future release
* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
adb: unable to connect for backup: cannot connect to daemon
Extracting tmp\whatsapp.ab file.
Traceback (most recent call last):
  File "C:\Users\michele\Desktop\IT\Code\Python\mwatoi\main.py", line 68, in <module>
    with tarfile.open('tmp\whatsapp.tar') as tp:
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 1613, in open
    return func(name, "r", fileobj, **kwargs)
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 1686, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 1663, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 1523, in __init__
    self.firstmember = self.next()
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 2358, in next
    raise e
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 2331, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 1113, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 301, in read
    return self._buffer.read(size)
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 439, in _read_gzip_header
    self._last_mtime) = struct.unpack("<BBIxx", self._read_exact(8))
  File "C:\Users\michele\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 425, in _read_exact
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by mukulkadel** [comment]
I think adb didn't start properly. Can you try killing it in task manager?

Reference: https://stackoverflow.com/questions/7327147/adb-error-cannot-connect-to-daemon
